--- 
### This playbook requires some additional attention.
##
## Required variable: remote_hosts
## Description: A list containing inventory hostnames to use as remote hosts for Ansible.
## - Provide an inventory group like: -e "remote_hosts={{ groups.some_inventory_group }}"
## - Provide a single machine like: -e "remote_hosts=['zmode800','zmode801']"
## - Provide a list ofmachines: -e "remote_hosts=['zmode800']"
##
## Default variables:
## - lynis_package      => Path to lynis archive
## - lynis_package_dir  => Path to house lynis archive extracts
## - lynis_package_path => Path to the lynis extracted archive
## - lynis_file_list    => List of paths to files generated and used by Lynis
## - mail_to_address    => List of e-mail addresses to send the reports to
##
## Command example:
## ansible-playbook playbooks/security_audit/lynis_v3.0.0_skeleton.yml \
## -e "remote_hosts={{ groups.some_inventory_group }}"

- name: Deploy and perform lynis audit
  hosts: localhost
  connection: local
  gather_facts: True
  become: True
  vars:
    lynis_package: '{{ inventory_dir }}/files/lynis-3.0.6.tar.gz'
    lynis_package_dir: /root/lynis
    lynis_package_path: /root/lynis/lynis
    lynis_file_list:
      - /tmp/lynis_run_audit_system_ansi.txt
      - /tmp/lynis_run_audit_system_clear.txt
      - /var/log/lynis.log
      - /var/log/lynis-report.dat
    lynis_report_archive: '{{ lynis_package_dir }}/lynis-{{ ansible_fqdn }}.zip'
    mail_to_address: '{{ hostvars["multiplay_vars_stub"].mail_to_address | default([]) }}'
  tasks:
    - name: Create lynis directory
      file:
        path: '{{ lynis_package_dir }}'
        state: directory
        owner: root
        group: root

    - name: Extract lynis package on targets
      unarchive:
        src: '{{ lynis_package }}'
        dest: '{{ lynis_package_dir }}'
        owner: root
        group: root

    - name: Run lynis audit
      shell: >
          ./lynis audit system --no-colors | tee /tmp/lynis_run_audit_system_ansi.txt &&
          cat /tmp/lynis_run_audit_system_ansi.txt | 
          sed 's/\x1B[@A-Z\\\]^_]\|\x1B\[[0-9:;<=>?]*[-!"#$%&'"'"'()*+,.\/]*[][\\@A-Z^_`a-z{|}~]//g' >
          /tmp/lynis_run_audit_system_clear.txt
      register: audit_system_output
      args:
        chdir: '{{ lynis_package_path }}'

    - name: Archive files due to size
      archive:
        path: '{{ lynis_file_list }}'
        format: zip
        dest: '{{ lynis_report_archive }}'

    # - name: Make mail body
    #   command: cat /tmp/lynis_run_audit_system_clear.txt
    #   register: mailbody

    # - name: Send mail report
    #   mail:
    #     to: '{{ mail_to_address }}'
    #     subject: Lynis system audit | {{ ansible_fqdn }} | {{ ansible_date_time.date }} {{ ansible_date_time.time }}
    #     body: '{{ mailbody.stdout }}'
    #     attach: '{{ lynis_file_list }}'
    #   when:
    #     - mail_to_address | length > 0

    # - name: Cleanup lynis files
    #   file:
    #     path: '{{ item }}'
    #     state: absent
    #   loop: '{{ lynis_file_list + [lynis_package_dir] }}'
